/**
 * @tracearr/shared - Shared types, schemas, and constants
 */

// Type exports
export type {
  // Server
  ServerType,
  Server,
  // User
  User,
  ServerUser,
  ServerUserWithIdentity,
  ServerUserDetail,
  ServerUserFullDetail,
  ViolationSummary,
  UserRole,
  AuthUser,
  UserLocation,
  UserDevice,
  // Session
  SessionState,
  MediaType,
  Session,
  SessionWithDetails,
  ActiveSession,
  SourceVideoDetails,
  SourceAudioDetails,
  StreamVideoDetails,
  StreamAudioDetails,
  TranscodeInfo,
  SubtitleInfo,
  StreamDetailFields,
  // Rule
  RuleType,
  ImpossibleTravelParams,
  SimultaneousLocationsParams,
  DeviceVelocityParams,
  ConcurrentStreamsParams,
  GeoRestrictionMode,
  GeoRestrictionParams,
  AccountInactivityUnit,
  AccountInactivityParams,
  RuleParams,
  Rule,
  // Rule V2
  Operator,
  ConditionField,
  ConditionValue,
  Condition,
  ConditionGroup,
  RuleConditions,
  ActionType,
  Action,
  LogOnlyAction,
  NotifyAction,
  AdjustTrustAction,
  SetTrustAction,
  ResetTrustAction,
  KillStreamAction,
  MessageClientAction,
  NotificationChannelV2,
  RuleActions,
  RuleV2,
  ActionResult,
  VideoResolution,
  DeviceType,
  Platform,
  MediaTypeEnum,
  TranscodingConditionValue,
  // Violation
  ViolationSeverity,
  Violation,
  ViolationWithDetails,
  ViolationSessionInfo,
  // Evidence
  ConditionEvidence,
  GroupEvidence,
  // Stats
  DashboardStats,
  PlayStats,
  UserStats,
  LocationStats,
  LocationStatsSummary,
  LocationStatsResponse,
  LibraryStats,
  DayOfWeekStats,
  HourOfDayStats,
  QualityStats,
  TopUserStats,
  TopContentStats,
  PlatformStats,
  // Server resource stats
  ServerResourceDataPoint,
  ServerResourceStats,
  // Server bandwidth stats
  ServerBandwidthDataPoint,
  ServerBandwidthStats,
  // Settings
  Settings,
  WebhookFormat,
  UnitSystem,
  // Tailscale
  TailscaleStatus,
  TailscaleExitNode,
  TailscaleInfo,
  // Tautulli import
  TautulliImportProgress,
  TautulliImportResult,
  // Jellystat import
  JellystatImportProgress,
  JellystatImportResult,
  // Library sync
  LibrarySyncProgress,
  // Heavy ops coordination
  HeavyOpsWaitingFor,
  // Maintenance jobs
  MaintenanceJobType,
  MaintenanceJobStatus,
  MaintenanceJobProgress,
  MaintenanceJobResult,
  // Running tasks
  RunningTaskType,
  RunningTask,
  RunningTasksResponse,
  // WebSocket
  ServerToClientEvents,
  ClientToServerEvents,
  // API
  PaginatedResponse,
  ApiError,
  // History page types
  HistoryAggregates,
  HistorySessionResponse,
  FilterOptionItem,
  UserFilterOption,
  ServerFilterOption,
  CountryOption,
  HistoryFilterOptions,
  RulesFilterOptions,
  // Mobile
  MobileToken,
  MobileSession,
  MobileConfig,
  MobilePairRequest,
  MobilePairResponse,
  MobilePairTokenResponse,
  MobileQRPayload,
  NotificationEventType,
  NotificationPreferences,
  RateLimitStatus,
  NotificationPreferencesWithStatus,
  NotificationChannel,
  NotificationChannelRouting,
  EncryptedPushPayload,
  PushNotificationPayload,
  // SSE (Server-Sent Events)
  SSEConnectionState,
  PlexSSENotification,
  PlexPlaySessionNotification,
  PlexActivityNotification,
  PlexStatusNotification,
  PlexTranscodeNotification,
  SSEConnectionStatus,
  // Termination logs
  TerminationTrigger,
  TerminationLogWithDetails,
  // Plex server discovery
  PlexDiscoveredConnection,
  PlexDiscoveredServer,
  PlexAvailableServersResponse,
  // Plex account management
  PlexAccount,
  PlexAccountsResponse,
  LinkPlexAccountRequest,
  LinkPlexAccountResponse,
  UnlinkPlexAccountResponse,
  // Version
  VersionInfo,
  // Engagement tracking
  EngagementTier,
  UserBehaviorType,
  ContentEngagement,
  TopContentEngagement,
  ShowEngagement,
  UserEngagementProfile,
  EngagementTierBreakdown,
  EngagementStats,
  ShowStatsResponse,
  // Device compatibility
  DeviceCompatibilityRow,
  DeviceCompatibilityResponse,
  DeviceCompatibilityMatrix,
  DeviceHealthRow,
  DeviceHealthResponse,
  TranscodeHotspotRow,
  TranscodeHotspotsResponse,
  // Top transcoding users
  TopTranscodingUserRow,
  TopTranscodingUsersResponse,
  // Bandwidth stats
  DailyBandwidthRow,
  DailyBandwidthResponse,
  BandwidthTopUser,
  BandwidthTopUsersResponse,
  BandwidthSummary,
  // Library statistics
  LibraryStatsResponse,
  GrowthDataPoint,
  LibraryGrowthResponse,
  QualityDataPoint,
  LibraryQualityResponse,
  StorageHistoryPoint,
  StoragePrediction,
  LibraryStorageResponse,
  MatchType,
  DuplicateItem,
  DuplicateGroup,
  DuplicatesSummary,
  DuplicatesResponse,
  StaleCategory,
  StaleItem,
  StaleSummary,
  StaleResponse,
  WatchItem,
  WatchSummary,
  WatchResponse,
  CompletionStatus,
  CompletionItem,
  SeasonCompletion,
  SeriesCompletion,
  CompletionSummary,
  CompletionPaginationInfo,
  CompletionResponse,
  BingeShow,
  HourlyDistribution,
  MonthlyTrend,
  PatternsResponse,
  ValueCategory,
  RoiItem,
  RoiSummary,
  ValueThresholds,
  RoiResponse,
  TopMovie,
  TopMoviesSummary,
  TopMoviesResponse,
  TopShow,
  TopShowsSummary,
  TopShowsResponse,
  CodecEntry,
  CodecBreakdown,
  LibraryCodecsResponse,
  ResolutionEntry,
  ResolutionBreakdown,
  LibraryResolutionResponse,
} from './types.js';

// Schema exports
export {
  // Common
  uuidSchema,
  paginationSchema,
  booleanStringSchema,
  // Auth
  loginSchema,
  callbackSchema,
  // Server
  createServerSchema,
  serverIdParamSchema,
  reorderServersSchema,
  updateServerSchema,
  // User
  updateUserSchema,
  updateUserIdentitySchema,
  userIdParamSchema,
  // Session
  sessionQuerySchema,
  historyQuerySchema,
  historyAggregatesQuerySchema,
  sessionIdParamSchema,
  terminateSessionBodySchema,
  // Rule
  impossibleTravelParamsSchema,
  simultaneousLocationsParamsSchema,
  deviceVelocityParamsSchema,
  concurrentStreamsParamsSchema,
  geoRestrictionParamsSchema,
  accountInactivityParamsSchema,
  ruleParamsSchema,
  createRuleSchema,
  updateRuleSchema,
  ruleIdParamSchema,
  // Rule V2
  createRuleV2Schema,
  updateRuleV2Schema,
  // Bulk operations
  bulkUpdateRulesSchema,
  bulkDeleteRulesSchema,
  bulkMigrateRulesSchema,
  // Violation
  violationSortFieldSchema,
  violationQuerySchema,
  violationIdParamSchema,
  // Stats
  serverIdFilterSchema,
  dashboardQuerySchema,
  timezoneSchema,
  statsQuerySchema,
  locationStatsQuerySchema,
  // Settings
  updateSettingsSchema,
  // Tailscale
  tailscaleEnableSchema,
  tailscaleExitNodeSchema,
  // Tautulli import
  tautulliImportSchema,
  // Jellystat import
  jellystatPlayStateSchema,
  jellystatTranscodingInfoSchema,
  jellystatPlaybackActivitySchema,
  jellystatBackupSchema,
  jellystatImportBodySchema,
  importJobStatusSchema,
  // Engagement tracking
  engagementTierSchema,
  userBehaviorTypeSchema,
  engagementQuerySchema,
  showsQuerySchema,
  // Library stats
  libraryStatsQuerySchema,
  libraryGrowthQuerySchema,
  libraryQualityQuerySchema,
  libraryStorageQuerySchema,
  libraryDuplicatesQuerySchema,
  libraryStaleQuerySchema,
  libraryWatchQuerySchema,
  libraryRoiQuerySchema,
  libraryPatternsQuerySchema,
  libraryCompletionQuerySchema,
  topContentQuerySchema,
} from './schemas.js';

// Schema input type exports
export type {
  LoginInput,
  CallbackInput,
  CreateServerInput,
  ReorderServersInput,
  UpdateServerInput,
  UpdateUserInput,
  UpdateUserIdentityInput,
  SessionQueryInput,
  HistoryQueryInput,
  HistoryAggregatesQueryInput,
  CreateRuleInput,
  UpdateRuleInput,
  // Rule V2 types
  CreateRuleV2Input,
  UpdateRuleV2Input,
  // Bulk operations types
  BulkUpdateRulesInput,
  BulkDeleteRulesInput,
  BulkMigrateRulesInput,
  ViolationQueryInput,
  ViolationSortField,
  ServerIdFilterInput,
  DashboardQueryInput,
  StatsQueryInput,
  LocationStatsQueryInput,
  UpdateSettingsInput,
  TautulliImportInput,
  // Jellystat types
  JellystatPlayState,
  JellystatTranscodingInfo,
  JellystatPlaybackActivity,
  JellystatBackup,
  JellystatImportBody,
  ImportJobStatus,
  // Engagement tracking
  EngagementQueryInput,
  ShowsQueryInput,
  // Library stats
  LibraryStatsQueryInput,
  LibraryGrowthQueryInput,
  LibraryQualityQueryInput,
  LibraryStorageQueryInput,
  LibraryDuplicatesQueryInput,
  LibraryStaleQueryInput,
  LibraryWatchQueryInput,
  LibraryRoiQueryInput,
  LibraryPatternsQueryInput,
  LibraryCompletionQueryInput,
  TopContentQueryInput,
  // Session target type
  SessionTarget,
} from './schemas.js';

// Constant exports
export {
  RULE_DEFAULTS,
  RULE_DISPLAY_NAMES,
  SEVERITY_LEVELS,
  getSeverityPriority,
  type SeverityPriority,
  WS_EVENTS,
  REDIS_KEYS,
  setRedisPrefix,
  getRedisPrefix,
  CACHE_TTL,
  NOTIFICATION_EVENTS,
  API_VERSION,
  API_BASE_PATH,
  JWT_CONFIG,
  POLLING_INTERVALS,
  POLLER_CONFIG,
  PAGINATION,
  GEOIP_CONFIG,
  TIME_MS,
  SESSION_LIMITS,
  SESSION_WRITE_RETRY,
  SERVER_STATS_CONFIG,
  BANDWIDTH_STATS_CONFIG,
  // SSE
  SSE_CONFIG,
  PLEX_SSE_EVENTS,
  SSE_STATE,
  // Unit conversion
  UNIT_CONVERSION,
  kmToMiles,
  milesToKm,
  formatDistance,
  formatSpeed,
  formatBitrate,
  formatMediaTech,
  getResolutionLabel,
  formatResolutionDisplay,
  type ResolutionLabel,
  formatAudioChannels,
  getDistanceUnit,
  getSpeedUnit,
  toMetricDistance,
  fromMetricDistance,
  formatConditionFieldValue,
  // Server colors
  SERVER_COLOR_PALETTE,
  SERVER_TYPE_BRAND_COLORS,
  pickServerColor,
  // Timezone utilities
  getClientTimezone,
  isValidTimezone,
} from './constants.js';

// Role helper exports
export { ROLE_PERMISSIONS, canLogin, hasMinRole, isOwner, isActive } from './types.js';

// Session constants
export { MEDIA_TYPES, DEFAULT_STREAM_DETAILS } from './types.js';

// Violation utilities
export {
  collectViolationSessions,
  getViolationDescription,
  getViolationDetails,
  formatEvidenceDescription,
  formatEvidenceDetails,
  CONDITION_FIELD_LABELS,
  OPERATOR_LABELS,
} from './violations.js';
